2023-06-19 09:35:53,397 INFO    StreamThr :21144 [internal.py:wandb_internal():88] W&B internal server running at pid: 21144, started at: 2023-06-19 09:35:53.391957
2023-06-19 09:35:53,400 DEBUG   HandlerThread:21144 [handler.py:handle_request():138] handle_request: status
2023-06-19 09:35:53,407 DEBUG   SenderThread:21144 [sender.py:send_request():317] send_request: status
2023-06-19 09:35:53,413 INFO    WriterThread:21144 [datastore.py:open_for_write():75] open: saved_models/codeparrot-clean/2023-06-19_09-34-39/wandb/offline-run-20230619_093553-2kt5bevq/run-2kt5bevq.wandb
2023-06-19 09:35:53,425 DEBUG   HandlerThread:21144 [handler.py:handle_request():138] handle_request: run_start
2023-06-19 09:35:53,435 DEBUG   HandlerThread:21144 [meta.py:__init__():34] meta init
2023-06-19 09:35:53,436 DEBUG   HandlerThread:21144 [meta.py:__init__():49] meta init done
2023-06-19 09:35:53,436 DEBUG   HandlerThread:21144 [meta.py:probe():215] probe
2023-06-19 09:35:53,445 DEBUG   HandlerThread:21144 [git.py:repo():40] git repository is invalid
2023-06-19 09:35:53,445 DEBUG   HandlerThread:21144 [meta.py:_save_pip():53] save pip
2023-06-19 09:35:53,454 DEBUG   HandlerThread:21144 [meta.py:_save_pip():67] save pip done
2023-06-19 09:35:53,454 DEBUG   HandlerThread:21144 [meta.py:_save_conda():74] save conda
2023-06-19 09:35:57,468 DEBUG   HandlerThread:21144 [meta.py:_save_conda():84] save conda done
2023-06-19 09:35:57,468 DEBUG   HandlerThread:21144 [meta.py:probe():253] probe done
2023-06-19 09:41:43,549 INFO    MainThread:21144 [internal.py:handle_exit():78] Internal process exited
2023-06-19 09:41:43,550 WARNING MsgRouterThr:21144 [router.py:message_loop():74] EOFError seen in message_loop
