2023-06-19 07:34:14,631 INFO    StreamThr :158318 [internal.py:wandb_internal():88] W&B internal server running at pid: 158318, started at: 2023-06-19 07:34:14.626604
2023-06-19 07:34:14,638 DEBUG   HandlerThread:158318 [handler.py:handle_request():138] handle_request: status
2023-06-19 07:34:14,648 DEBUG   SenderThread:158318 [sender.py:send_request():317] send_request: status
2023-06-19 07:34:14,654 INFO    WriterThread:158318 [datastore.py:open_for_write():75] open: saved_models/codeparrot-clean/2023-06-19_07-34-04/wandb/offline-run-20230619_073414-uh3avsbp/run-uh3avsbp.wandb
2023-06-19 07:34:14,661 DEBUG   HandlerThread:158318 [handler.py:handle_request():138] handle_request: run_start
2023-06-19 07:34:14,673 DEBUG   HandlerThread:158318 [meta.py:__init__():34] meta init
2023-06-19 07:34:14,673 DEBUG   HandlerThread:158318 [meta.py:__init__():49] meta init done
2023-06-19 07:34:14,673 DEBUG   HandlerThread:158318 [meta.py:probe():215] probe
2023-06-19 07:34:14,682 DEBUG   HandlerThread:158318 [git.py:repo():40] git repository is invalid
2023-06-19 07:34:14,682 DEBUG   HandlerThread:158318 [meta.py:_save_pip():53] save pip
2023-06-19 07:34:14,688 DEBUG   HandlerThread:158318 [meta.py:_save_pip():67] save pip done
2023-06-19 07:34:14,688 DEBUG   HandlerThread:158318 [meta.py:_save_conda():74] save conda
2023-06-19 07:34:22,568 DEBUG   HandlerThread:158318 [meta.py:_save_conda():84] save conda done
2023-06-19 07:34:22,569 DEBUG   HandlerThread:158318 [meta.py:probe():253] probe done
2023-06-19 07:43:46,848 INFO    MainThread:158318 [internal.py:handle_exit():78] Internal process exited
2023-06-19 07:43:46,849 WARNING MsgRouterThr:158318 [router.py:message_loop():74] EOFError seen in message_loop
