2023-06-19 09:24:33,916 INFO    StreamThr :16411 [internal.py:wandb_internal():88] W&B internal server running at pid: 16411, started at: 2023-06-19 09:24:33.909757
2023-06-19 09:24:33,921 DEBUG   HandlerThread:16411 [handler.py:handle_request():138] handle_request: status
2023-06-19 09:24:33,923 DEBUG   SenderThread:16411 [sender.py:send_request():317] send_request: status
2023-06-19 09:24:33,925 INFO    WriterThread:16411 [datastore.py:open_for_write():75] open: saved_models/codeparrot-clean/2023-06-19_09-24-07/wandb/offline-run-20230619_092433-35h9pu59/run-35h9pu59.wandb
2023-06-19 09:24:33,935 DEBUG   HandlerThread:16411 [handler.py:handle_request():138] handle_request: run_start
2023-06-19 09:24:33,943 DEBUG   HandlerThread:16411 [meta.py:__init__():34] meta init
2023-06-19 09:24:33,944 DEBUG   HandlerThread:16411 [meta.py:__init__():49] meta init done
2023-06-19 09:24:33,944 DEBUG   HandlerThread:16411 [meta.py:probe():215] probe
2023-06-19 09:24:33,955 DEBUG   HandlerThread:16411 [git.py:repo():40] git repository is invalid
2023-06-19 09:24:33,955 DEBUG   HandlerThread:16411 [meta.py:_save_pip():53] save pip
2023-06-19 09:24:33,962 DEBUG   HandlerThread:16411 [meta.py:_save_pip():67] save pip done
2023-06-19 09:24:33,962 DEBUG   HandlerThread:16411 [meta.py:_save_conda():74] save conda
2023-06-19 09:24:38,174 DEBUG   HandlerThread:16411 [meta.py:_save_conda():84] save conda done
2023-06-19 09:24:38,175 DEBUG   HandlerThread:16411 [meta.py:probe():253] probe done
2023-06-19 09:28:56,034 INFO    MainThread:16411 [internal.py:handle_exit():78] Internal process exited
2023-06-19 09:28:56,035 WARNING MsgRouterThr:16411 [router.py:message_loop():74] EOFError seen in message_loop
