2023-06-19 07:27:53,091 INFO    StreamThr :155554 [internal.py:wandb_internal():88] W&B internal server running at pid: 155554, started at: 2023-06-19 07:27:53.086484
2023-06-19 07:27:53,094 DEBUG   HandlerThread:155554 [handler.py:handle_request():138] handle_request: status
2023-06-19 07:27:53,103 DEBUG   SenderThread:155554 [sender.py:send_request():317] send_request: status
2023-06-19 07:27:53,106 INFO    WriterThread:155554 [datastore.py:open_for_write():75] open: saved_models/codeparrot-clean/2023-06-19_07-27-38/wandb/offline-run-20230619_072753-2spt4mqo/run-2spt4mqo.wandb
2023-06-19 07:27:53,128 DEBUG   HandlerThread:155554 [handler.py:handle_request():138] handle_request: run_start
2023-06-19 07:27:53,139 DEBUG   HandlerThread:155554 [meta.py:__init__():34] meta init
2023-06-19 07:27:53,139 DEBUG   HandlerThread:155554 [meta.py:__init__():49] meta init done
2023-06-19 07:27:53,140 DEBUG   HandlerThread:155554 [meta.py:probe():215] probe
2023-06-19 07:27:53,148 DEBUG   HandlerThread:155554 [git.py:repo():40] git repository is invalid
2023-06-19 07:27:53,149 DEBUG   HandlerThread:155554 [meta.py:_save_pip():53] save pip
2023-06-19 07:27:53,154 DEBUG   HandlerThread:155554 [meta.py:_save_pip():67] save pip done
2023-06-19 07:27:53,154 DEBUG   HandlerThread:155554 [meta.py:_save_conda():74] save conda
2023-06-19 07:28:00,970 DEBUG   HandlerThread:155554 [meta.py:_save_conda():84] save conda done
2023-06-19 07:28:00,970 DEBUG   HandlerThread:155554 [meta.py:probe():253] probe done
2023-06-19 07:33:51,248 INFO    MainThread:155554 [internal.py:handle_exit():78] Internal process exited
2023-06-19 07:33:51,249 WARNING MsgRouterThr:155554 [router.py:message_loop():74] EOFError seen in message_loop
