2023-06-18 23:36:22,473 INFO    StreamThr :38267 [internal.py:wandb_internal():88] W&B internal server running at pid: 38267, started at: 2023-06-18 23:36:22.466378
2023-06-18 23:36:22,483 DEBUG   HandlerThread:38267 [handler.py:handle_request():138] handle_request: status
2023-06-18 23:36:22,490 DEBUG   SenderThread:38267 [sender.py:send_request():317] send_request: status
2023-06-18 23:36:22,493 INFO    WriterThread:38267 [datastore.py:open_for_write():75] open: saved_models/codeparrot-clean/2023-06-18_23-36-13/wandb/offline-run-20230618_233622-1nksx1pd/run-1nksx1pd.wandb
2023-06-18 23:36:22,493 DEBUG   HandlerThread:38267 [handler.py:handle_request():138] handle_request: run_start
2023-06-18 23:36:22,522 DEBUG   HandlerThread:38267 [meta.py:__init__():34] meta init
2023-06-18 23:36:22,523 DEBUG   HandlerThread:38267 [meta.py:__init__():49] meta init done
2023-06-18 23:36:22,523 DEBUG   HandlerThread:38267 [meta.py:probe():215] probe
2023-06-18 23:36:22,538 DEBUG   HandlerThread:38267 [git.py:repo():40] git repository is invalid
2023-06-18 23:36:22,539 DEBUG   HandlerThread:38267 [meta.py:_save_pip():53] save pip
2023-06-18 23:36:22,544 DEBUG   HandlerThread:38267 [meta.py:_save_pip():67] save pip done
2023-06-18 23:36:22,545 DEBUG   HandlerThread:38267 [meta.py:_save_conda():74] save conda
2023-06-18 23:36:28,494 DEBUG   HandlerThread:38267 [meta.py:_save_conda():84] save conda done
2023-06-18 23:36:28,495 DEBUG   HandlerThread:38267 [meta.py:probe():253] probe done
2023-06-19 07:20:42,223 INFO    MainThread:38267 [internal.py:handle_exit():78] Internal process exited
2023-06-19 07:20:42,224 WARNING MsgRouterThr:38267 [router.py:message_loop():74] EOFError seen in message_loop
