2023-06-19 08:53:33,555 INFO    StreamThr :6499 [internal.py:wandb_internal():88] W&B internal server running at pid: 6499, started at: 2023-06-19 08:53:33.549669
2023-06-19 08:53:33,572 DEBUG   HandlerThread:6499 [handler.py:handle_request():138] handle_request: status
2023-06-19 08:53:33,573 DEBUG   SenderThread:6499 [sender.py:send_request():317] send_request: status
2023-06-19 08:53:33,581 INFO    WriterThread:6499 [datastore.py:open_for_write():75] open: saved_models/codeparrot-clean/2023-06-19_08-53-23/wandb/offline-run-20230619_085333-15e9p5h3/run-15e9p5h3.wandb
2023-06-19 08:53:33,582 DEBUG   HandlerThread:6499 [handler.py:handle_request():138] handle_request: run_start
2023-06-19 08:53:33,593 DEBUG   HandlerThread:6499 [meta.py:__init__():34] meta init
2023-06-19 08:53:33,594 DEBUG   HandlerThread:6499 [meta.py:__init__():49] meta init done
2023-06-19 08:53:33,594 DEBUG   HandlerThread:6499 [meta.py:probe():215] probe
2023-06-19 08:53:33,602 DEBUG   HandlerThread:6499 [git.py:repo():40] git repository is invalid
2023-06-19 08:53:33,603 DEBUG   HandlerThread:6499 [meta.py:_save_pip():53] save pip
2023-06-19 08:53:33,613 DEBUG   HandlerThread:6499 [meta.py:_save_pip():67] save pip done
2023-06-19 08:53:33,613 DEBUG   HandlerThread:6499 [meta.py:_save_conda():74] save conda
2023-06-19 08:53:40,555 DEBUG   HandlerThread:6499 [meta.py:_save_conda():84] save conda done
2023-06-19 08:53:40,555 DEBUG   HandlerThread:6499 [meta.py:probe():253] probe done
2023-06-19 09:15:26,044 INFO    MainThread:6499 [internal.py:handle_exit():78] Internal process exited
2023-06-19 09:15:26,045 WARNING MsgRouterThr:6499 [router.py:message_loop():74] EOFError seen in message_loop
